"""Create Item model

Revision ID: 3e8f7b0fc40a
Revises: 
Create Date: 2026-02-17 07:17:53.990596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '3e8f7b0fc40a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'items',
        sa.Column(
            'id',
            sa.Integer(),
            autoincrement=True,
            nullable=False
        ),
        sa.Column(
            'text',
            sa.Text(),
            nullable=False,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('utc', now())"),
            nullable=False
        ),
        sa.PrimaryKeyConstraint(
            'id',
            name=op.f('pk_items')
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')
    # ### end Alembic commands ###
