"""add index ix_items_created_at_id for pagination

Revision ID: 504f9bfa53a0
Revises: 3e8f7b0fc40a
Create Date: 2026-02-18 13:24:22.225132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '504f9bfa53a0'
down_revision: Union[str, Sequence[str], None] = '3e8f7b0fc40a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        'ix_items_created_at_id',
        'items',
        [
            sa.literal_column('created_at DESC'),
            sa.literal_column('id DESC')
        ],
        unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_items_created_at_id', table_name='items')
    # ### end Alembic commands ###
